### ISSUE TITLE
lingering larval states and policies

### ISSUE THREAD

**Issue by cagney** [libreswan/libreswan#1554]
Run:
```
grep -e 'IGNORE: policy ' -e 'IGNORE: state ' testing/pluto/*/OUTPUT/*.console.verbose.txt
```
blocks #511
blocked by:

- [ ]  cleaning up the IKEv2 CHILD SA's spi #454 
- [ ]  ikev2-ondemand-01-instance-route: established ondemand child sa should delete larval state #1110 
- [ ]  lingering <<000 192.1.3.209/32 -0-> 192.1.2.23/32 => %pass 0 oe-failing>> bare shunt in certoe-18-pass-then-go-slash32-keyingtries1 #530 
- [ ]  f35: certoe-13-poc-del-slash24 leaves a larval state behind #577
